In [10]:
#1
import numpy as np
array = np.arange(50,100)
array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
#2 arvan shirheg 0
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#2 arvan shirheg 1
import numpy as np
x=np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
#2 arvan shirheg 6
import numpy as np
x=np.zeros(10)+6
print(x)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [12]:
#3 
data1= np.arange(20,32)
a= np.reshape(data1,(3,4))
print(a)


[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [21]:
#4
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#5
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
#6
import numpy as np
b = np.array([[1,3,5,7],[9,12,15,18],[3,2,6,9]])
print(sum(sum(b)))
print(b.sum(axis=0))
print(b.sum(axis=1))

90
[13 17 26 34]
[16 54 20]


In [68]:
#7
import numpy as np 

#seasons
Seasons = ["2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]
Sdict = {"2012":7,"2013":8,"2014":9, "2015":10,"2016":11,"2017":12,"2018":13,"2019":14,"2020":15,"2021":16}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6}

#Salaries
KobeBryant_Salary = [27849149,30453805,23500000,25000000,0,0,0,0,0,0]
JoeJohnson_Salary = [19752645,21466718,23180790,22309344,11000000,10254904,0,2564753,151821,0]
LeBronJames_Salary = [17545000,19067500,20644400,22970500,30963450,33285709,35654150,37436858,39219566,41180544]
CarmeloAnthony_Salary = [19450000,22407474,22458000,22875000,24559380,26243760,2393887,2159029,2564753,2641691]
DwightHoward_Salary = [19536360,20513178,21436271,22359364,23500000,23500000,18919725,24256725,2564753,2641691]
ChrisBosh_Salary = [17545000,19067500,20644400,22192730,23741060,25289390,26837720,0,0,0]
ChrisPaul_Salary = [17779458,18668431,20068563,21468695,22868827,24268959,35654150,38506482,41358814,30800000]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary])

#Games 
KobeBryant_G = [78,6,35,66,0,0,0,0,0,0]
JoeJohnson_G = [72,79,80,81,24,57,78,55,0,0]
LeBronJames_G = [76,77,69,76,74,82,55,67,45,48]
CarmeloAnthony_G = [67,77,40,72,74,78,10,58,69,58]
DwightHoward_G = [76,71,41,71,74,81,9,69,69,47]
ChrisBosh_G = [74,79,44,53,0,0,0,0,0,0]
ChrisPaul_G = [70,62,82,74,61,58,58,70,70,58]  
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G])

#Field Goals
KobeBryant_FG = [738,31,266,398,0,0,0,0,0,0]
JoeJohnson_FG = [445,462,446,377,247,130,273,95,51,1]
LeBronJames_FG = [765,767,624,737,736,857,558,643,422,556]
CarmeloAnthony_FG = [669,743,358,567,602,472,49,336,327,270]
DwightHoward_FG = [470,473,251,372,388,506,43,202,178,91]
ChrisBosh_FG = [485,492,343,358,0,0,0,0,0,0]
ChrisPaul_FG = [412,406,568,515,374,367,302,434,439,325]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG])

In [53]:
# 7 salary
print("Salary Baganiin niilber = ", Salary.sum(axis=0))
print("Salary Moriin niilber = ", Salary.sum(axis=1))

Salary Baganiin niilber =  [139457612 151644606 151932424 159175633 136632717 142842722 119459632
 104923847  85859707  77263926]
Salary Moriin niilber =  [106802954 110680975 297967677 147752974 179228067 155317800 271442379]


In [69]:
#7 games
print("Games Baganiin niilber = ", Games.sum(axis=0))
print("Games Moriin niilber = ", Games.sum(axis=1))

Games Baganiin niilber =  [513 451 391 493 307 356 210 319 253 211]
Games Moriin niilber =  [185 526 669 603 608 250 663]


In [70]:
# 7 FieldGoals 
print("FieldGoals Baganiin niilber = ", FieldGoals.sum(axis=0))
print("FieldGoals Moriin niilber = ", FieldGoals.sum(axis=1))

FieldGoals Baganiin niilber =  [3984 3374 2856 3324 2347 2332 1225 1710 1417 1243]
FieldGoals Moriin niilber =  [1433 2527 6665 4393 2974 1678 4142]
